_id: 7nxDYi7V2mtlvqmV
name: Society-Values
type: null
img: icons/svg/d20-grey.svg
folder: fhkT8z8QarD3U3n2
sort: 0
ownership:
  default: 0
  lKC5x4Yf023Bizof: 3
flags:
  better-rolltables: {}
_stats:
  compendiumSource: Compendium.swnr.wwn-gm-sub-tables.RollTable.7nxDYi7V2mtlvqmV
  duplicateSource: null
  exportSource: null
  coreVersion: '13.350'
  systemId: swnr
  systemVersion: 2.1.0
  createdTime: 1754271915093
  modifiedTime: 1754271915093
  lastModifiedBy: lKC5x4Yf023Bizof
system: {}
effects: []
results:
  - _id: DOEOxdGdduGkkqX2
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 1
      - 2
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.DOEOxdGdduGkkqX2'
  - _id: Ul4aV39b655EvbbG
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 3
      - 4
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.Ul4aV39b655EvbbG'
  - _id: EPnUvuth4e7BI8qP
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 5
      - 6
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.EPnUvuth4e7BI8qP'
  - _id: THj976NGMFSvOMls
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 7
      - 8
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.THj976NGMFSvOMls'
  - _id: xUgazEpWJ8XXES7M
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 9
      - 10
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.xUgazEpWJ8XXES7M'
  - _id: FxWmhCuDVVfz4UeG
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 11
      - 12
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.FxWmhCuDVVfz4UeG'
  - _id: liR4EVvZe9m1OaPR
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 13
      - 14
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.liR4EVvZe9m1OaPR'
  - _id: hke0Lo2riB3ANxt4
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 15
      - 16
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hke0Lo2riB3ANxt4'
  - _id: LixI0QnXv6acRpuK
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 17
      - 18
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.LixI0QnXv6acRpuK'
  - _id: dHX53u6jAolWcCSH
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 19
      - 20
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.dHX53u6jAolWcCSH'
  - _id: anXEXptlOgtUTUC4
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 21
      - 22
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.anXEXptlOgtUTUC4'
  - _id: rcgiXEbmvJy7piLO
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 23
      - 24
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.rcgiXEbmvJy7piLO'
  - _id: JKT8fk9ZswuOUnHd
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 25
      - 26
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.JKT8fk9ZswuOUnHd'
  - _id: PDAsbpz0ufyaLXGq
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 27
      - 28
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.PDAsbpz0ufyaLXGq'
  - _id: hOn8H0rYqsBOcvWW
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 29
      - 30
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hOn8H0rYqsBOcvWW'
  - _id: l9MnCM7UpfvvTe0F
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 31
      - 32
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.l9MnCM7UpfvvTe0F'
  - _id: tBmbY6gSmsFNaJ91
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 33
      - 34
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.tBmbY6gSmsFNaJ91'
  - _id: 48L77T1Zue7YtxuS
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 35
      - 36
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.48L77T1Zue7YtxuS'
  - _id: JT1FeHSHKwVPFlzC
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 37
      - 38
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.JT1FeHSHKwVPFlzC'
  - _id: u5SprA8y3UbUAYFK
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 39
      - 40
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.u5SprA8y3UbUAYFK'
  - _id: 5r1FrGyRoSyPAOZR
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 41
      - 42
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.5r1FrGyRoSyPAOZR'
  - _id: fKKCaftjE5SkoJkN
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 43
      - 44
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.fKKCaftjE5SkoJkN'
  - _id: FDcm5O0EdjnZQBpj
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 45
      - 46
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.FDcm5O0EdjnZQBpj'
  - _id: Yj6MMMTa1Blh8BoG
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 47
      - 48
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.Yj6MMMTa1Blh8BoG'
  - _id: eAkG336EfV0TTJVR
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 49
      - 50
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.eAkG336EfV0TTJVR'
  - _id: tbEUjixz3Ci3sgbQ
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 51
      - 52
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.tbEUjixz3Ci3sgbQ'
  - _id: 2MkeCBzRYnXURMPf
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 53
      - 54
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.2MkeCBzRYnXURMPf'
  - _id: cyev3RDo7OOTpCyb
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 55
      - 56
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.cyev3RDo7OOTpCyb'
  - _id: B6giyuJoGKAeMdbs
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 57
      - 58
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.B6giyuJoGKAeMdbs'
  - _id: rCo0Yh18e41uxsoc
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 59
      - 60
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.rCo0Yh18e41uxsoc'
  - _id: JwdXRjkTH1uwhCPr
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 61
      - 62
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.JwdXRjkTH1uwhCPr'
  - _id: 3znV7LBRbXYiQuMo
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 63
      - 64
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.3znV7LBRbXYiQuMo'
  - _id: hLu3UNN9kcJulB5M
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 65
      - 66
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hLu3UNN9kcJulB5M'
  - _id: MaVAkI9wNP2jmtCT
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 67
      - 68
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.MaVAkI9wNP2jmtCT'
  - _id: GCEvdvdtrHB83X5I
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 69
      - 70
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.GCEvdvdtrHB83X5I'
  - _id: KyQcgE8y1WCR9amN
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 71
      - 72
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.KyQcgE8y1WCR9amN'
  - _id: rQyAzq5j0MSzDzoR
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 73
      - 74
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.rQyAzq5j0MSzDzoR'
  - _id: hsHOM8xTeiJpoSf5
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 75
      - 76
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hsHOM8xTeiJpoSf5'
  - _id: WylvnuYr3nc7MIC8
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 77
      - 78
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.WylvnuYr3nc7MIC8'
  - _id: W36pC9d6HCp0imPO
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 79
      - 80
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.W36pC9d6HCp0imPO'
  - _id: F6nYpXMI3Mm6Lxe1
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 81
      - 82
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.F6nYpXMI3Mm6Lxe1'
  - _id: UKnCtXBnXMVGetOt
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 83
      - 84
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.UKnCtXBnXMVGetOt'
  - _id: bdzrF3BR87x4grUU
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 85
      - 86
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.bdzrF3BR87x4grUU'
  - _id: g41LzU573bWTjGV2
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 87
      - 88
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.g41LzU573bWTjGV2'
  - _id: Hm0J1p2ot5Rb9TFW
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 89
      - 90
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.Hm0J1p2ot5Rb9TFW'
  - _id: clZ9po4EYTOKKn88
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 91
      - 92
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.clZ9po4EYTOKKn88'
  - _id: XOfEMWcSX7ZJQ6UL
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 93
      - 94
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.XOfEMWcSX7ZJQ6UL'
  - _id: m03gFj04N6zY1VOh
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 95
      - 96
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.m03gFj04N6zY1VOh'
  - _id: HCLpZXTzQrRcgupc
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 97
      - 98
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.HCLpZXTzQrRcgupc'
  - _id: hITuh7WBGygjz7KT
    type: text
    text: null
    img: null
    weight: 2
    range:
      - 99
      - 100
    drawn: 0
    flags: {}
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hITuh7WBGygjz7KT'
_key: '!tables!7nxDYi7V2mtlvqmV'

