data:
  broken: false
  cost: 4000
  costMultiplier: true
  description: >-
    Environmental Power: The drone draws operating power from sunlight or thermal variances. It can operate indefinitely so long as it can draw power from its environment.
  mass: 1
  massMultiplier: false
  power: 0
  powerMultiplier: false
  type: drone
img: systems/swnr/assets/icons/game-icons.net/item-icons/gps.svg
name: Environmental Power
type: shipFitting
