/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class SWNActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Core prepareBaseData() runs _clearData(), which (as of v13/v14)
    // initializes this.tokenActiveEffectChanges, this.overrides, statuses,
    // and _completedActiveEffectPhases. applyActiveEffects() relies on those,
    // so super MUST be called or effect application throws during _initialize.
    super.prepareBaseData();
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    super.prepareDerivedData();
    const actorData = this;
    const flags = actorData.flags.swnr || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
  * @override
  * Override the standard permission test for an Item.
  * Determine default artwork based on the provided item data.
  * @param {ItemData} itemData  The source item data.
  * @returns {{img: string}}    Candidate item image.
  */
  rollInitiative(options = {}) {
    // Render a flat modifier as a formula suffix. A negative becomes ` - n` rather
    // than ` + -n`, which the roll parser rejects; zero or unset contributes
    // nothing, so the formula stays clean when no modifier applies.
    const signed = (value) => {
      const n = Number(value);
      if (!n) {
        return '';
      }
      return n < 0 ? ` - ${Math.abs(n)}` : ` + ${n}`;
    };
    // Flat initiative modifier, e.g. CWN reflex cyberware. Lives on the base actor
    // (and on ships), so characters, npcs, and ships can all carry one.
    const initMod = (actor) => signed(actor.system.initiative?.mod);
    const die = (adv) => (adv ? "2d8kh1" : "1d8");

    // For starship actors, use the pilot's initiative. The ship's own modifier
    // applies either way -- it belongs to the hull, not to whoever is in the chair.
    if (this.type === "ship") {
      const shipMod = initMod(this);
      const pilotId = this.system.roles.bridge;
      if (pilotId && pilotId !== "") {
        const pilot = game.actors?.get(pilotId);
        if (pilot && pilot.type === "character") {
          const intMod = pilot.system.stats.int.mod;
          const dexMod = pilot.system.stats.dex.mod;
          const statMod = signed(intMod >= dexMod ? intMod : dexMod);
          // Use pilot's advInit flag if set.
          const adv = pilot.system?.tweak?.advInit || false;
          const formula = `${die(adv)}${statMod}${initMod(pilot)}${shipMod}`;
          return new Roll(formula, pilot.getRollData());
        }
      }
      // No pilot assigned: the ship rolls on its own, with no stat to draw on.
      return new Roll(`${die(false)}${shipMod}`, this.getRollData());
    }
  
    // Regular initiative roll.
    const adv = this.system?.tweak?.advInit || false;
    const formula = `${die(adv)} + @stats.dex.mod${initMod(this)}`;
    return new Roll(formula, this.getRollData());
  }
  
  static getDefaultArtwork(itemData) {
    let itemType = itemData.type;
    if (itemType in CONFIG.SWN.defaultImg) {
      return { img: `${CONFIG.SWN.actorIconPath}/${CONFIG.SWN.defaultImg[itemType]}`,
              texture: { src: `${CONFIG.SWN.actorIconPath}/${CONFIG.SWN.defaultImg[itemType]}` }
       };
    } else {
      return { texture: { src: this.DEFAULT_ICON } };
    }
  }
}
