name: Prodigy
type: feature
img: systems/swnr/assets/icons/game-icons.net/item-icons/edge.svg
folder: null
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  coreVersion: '12.331'
  systemId: swnr
  systemVersion: 2.0.0
  createdTime: 1739238988638
  modifiedTime: 1739238988638
sort: 0
_id: 3vkunhznrha449o0
system:
  description: Pick an attribute other than Constitution; its score becomes 18 and it grants a +3 modifier instead of +2. Characters benefiting from the Underdog Rule can't take this Edge.
  favorite: false
  level: 0
  type: edge
effects: []
_key: '!items!3vkunhznrha449o0'
