name: Environmental Power
type: shipFitting
img: systems/swnr/assets/icons/game-icons.net/item-icons/gps.svg
folder: null
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  coreVersion: '12.331'
  systemId: swnr
  systemVersion: 2.0.0
  createdTime: 1741813405607
  modifiedTime: 1741813405607
sort: 0
_id: 0jwoaz30pw55ptvi
system:
  description: 'Environmental Power: The drone draws operating power from sunlight or thermal variances. It can operate indefinitely so long as it can draw power from its environment.'
  favorite: false
  tl: null
  broken: false
  destroyed: false
  juryRigged: false
  cost: 4000
  costMultiplier: true
  mass: 1
  massMultiplier: false
  power: 0
  powerMultiplier: false
  minClass: fighter
  type: drone
  effect: ''
effects: []
_key: '!items!0jwoaz30pw55ptvi'
