_id: 7nxDYi7V2mtlvqmV
name: Society-Values
img: icons/svg/d20-grey.svg
description: Values of the Society
results:
  - _id: DOEOxdGdduGkkqX2
    flags: {}
    type: text
    text: Individual rights and freedom of action
    weight: 2
    range:
      - 1
      - 2
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.DOEOxdGdduGkkqX2'
  - _id: Ul4aV39b655EvbbG
    flags: {}
    type: text
    text: Courage and valiance in danger
    weight: 2
    range:
      - 3
      - 4
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.Ul4aV39b655EvbbG'
  - _id: EPnUvuth4e7BI8qP
    flags: {}
    type: text
    text: Honesty and truthfulness in speech
    weight: 2
    range:
      - 5
      - 6
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.EPnUvuth4e7BI8qP'
  - _id: THj976NGMFSvOMls
    flags: {}
    type: text
    text: Eloquence and social expertise
    weight: 2
    range:
      - 7
      - 8
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.THj976NGMFSvOMls'
  - _id: xUgazEpWJ8XXES7M
    flags: {}
    type: text
    text: Raw strength and personal prowess
    weight: 2
    range:
      - 9
      - 10
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.xUgazEpWJ8XXES7M'
  - _id: FxWmhCuDVVfz4UeG
    flags: {}
    type: text
    text: Discipline and obedience to the law
    weight: 2
    range:
      - 11
      - 12
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.FxWmhCuDVVfz4UeG'
  - _id: liR4EVvZe9m1OaPR
    flags: {}
    type: text
    text: Filial devotion to family and parents
    weight: 2
    range:
      - 13
      - 14
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.liR4EVvZe9m1OaPR'
  - _id: hke0Lo2riB3ANxt4
    flags: {}
    type: text
    text: Education and knowledge-seeking
    weight: 2
    range:
      - 15
      - 16
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hke0Lo2riB3ANxt4'
  - _id: LixI0QnXv6acRpuK
    flags: {}
    type: text
    text: Piety and devotion to the gods
    weight: 2
    range:
      - 17
      - 18
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.LixI0QnXv6acRpuK'
  - _id: dHX53u6jAolWcCSH
    flags: {}
    type: text
    text: Beauty and seductive charm
    weight: 2
    range:
      - 19
      - 20
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.dHX53u6jAolWcCSH'
  - _id: anXEXptlOgtUTUC4
    flags: {}
    type: text
    text: Conquest and domination of others
    weight: 2
    range:
      - 21
      - 22
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.anXEXptlOgtUTUC4'
  - _id: rcgiXEbmvJy7piLO
    flags: {}
    type: text
    text: Ascetic unworldliness and pious poverty
    weight: 2
    range:
      - 23
      - 24
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.rcgiXEbmvJy7piLO'
  - _id: JKT8fk9ZswuOUnHd
    flags: {}
    type: text
    text: Harmony with nature and existing life
    weight: 2
    range:
      - 25
      - 26
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.JKT8fk9ZswuOUnHd'
  - _id: PDAsbpz0ufyaLXGq
    flags: {}
    type: text
    text: Ethnic purity of blood and culture
    weight: 2
    range:
      - 27
      - 28
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.PDAsbpz0ufyaLXGq'
  - _id: hOn8H0rYqsBOcvWW
    flags: {}
    type: text
    text: Cunning and the ability to trick others
    weight: 2
    range:
      - 29
      - 30
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hOn8H0rYqsBOcvWW'
  - _id: l9MnCM7UpfvvTe0F
    flags: {}
    type: text
    text: Subtlety and indirectness of action
    weight: 2
    range:
      - 31
      - 32
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.l9MnCM7UpfvvTe0F'
  - _id: tBmbY6gSmsFNaJ91
    flags: {}
    type: text
    text: Prosperity and accruing material wealth
    weight: 2
    range:
      - 33
      - 34
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.tBmbY6gSmsFNaJ91'
  - _id: 48L77T1Zue7YtxuS
    flags: {}
    type: text
    text: Submission to the collective will or culture
    weight: 2
    range:
      - 35
      - 36
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.48L77T1Zue7YtxuS'
  - _id: JT1FeHSHKwVPFlzC
    flags: {}
    type: text
    text: Hardiness and endurance before woes
    weight: 2
    range:
      - 37
      - 38
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.JT1FeHSHKwVPFlzC'
  - _id: u5SprA8y3UbUAYFK
    flags: {}
    type: text
    text: Honor and maintaining one’s integrity
    weight: 2
    range:
      - 39
      - 40
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.u5SprA8y3UbUAYFK'
  - _id: 5r1FrGyRoSyPAOZR
    flags: {}
    type: text
    text: Sexual license and wantonness
    weight: 2
    range:
      - 41
      - 42
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.5r1FrGyRoSyPAOZR'
  - _id: fKKCaftjE5SkoJkN
    flags: {}
    type: text
    text: Submission to lawful authority
    weight: 2
    range:
      - 43
      - 44
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.fKKCaftjE5SkoJkN'
  - _id: FDcm5O0EdjnZQBpj
    flags: {}
    type: text
    text: Personal development and limit-pushing
    weight: 2
    range:
      - 45
      - 46
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.FDcm5O0EdjnZQBpj'
  - _id: Yj6MMMTa1Blh8BoG
    flags: {}
    type: text
    text: Justice and fairness between people
    weight: 2
    range:
      - 47
      - 48
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.Yj6MMMTa1Blh8BoG'
  - _id: eAkG336EfV0TTJVR
    flags: {}
    type: text
    text: Purging evil and expelling the wicked
    weight: 2
    range:
      - 49
      - 50
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.eAkG336EfV0TTJVR'
  - _id: tbEUjixz3Ci3sgbQ
    flags: {}
    type: text
    text: Personal sacrifice for one’s causes or purposes
    weight: 2
    range:
      - 51
      - 52
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.tbEUjixz3Ci3sgbQ'
  - _id: 2MkeCBzRYnXURMPf
    flags: {}
    type: text
    text: Building things in service of their posterity
    weight: 2
    range:
      - 53
      - 54
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.2MkeCBzRYnXURMPf'
  - _id: cyev3RDo7OOTpCyb
    flags: {}
    type: text
    text: Faithfulness towards one’s chosen friends
    weight: 2
    range:
      - 55
      - 56
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.cyev3RDo7OOTpCyb'
  - _id: B6giyuJoGKAeMdbs
    flags: {}
    type: text
    text: Dominating and possessing other people
    weight: 2
    range:
      - 57
      - 58
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.B6giyuJoGKAeMdbs'
  - _id: rCo0Yh18e41uxsoc
    flags: {}
    type: text
    text: Exploring the unknown and discovering secrets
    weight: 2
    range:
      - 59
      - 60
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.rCo0Yh18e41uxsoc'
  - _id: JwdXRjkTH1uwhCPr
    flags: {}
    type: text
    text: Seeking fortune in new places or new roles
    weight: 2
    range:
      - 61
      - 62
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.JwdXRjkTH1uwhCPr'
  - _id: 3znV7LBRbXYiQuMo
    flags: {}
    type: text
    text: Social progress toward some eventual utopia
    weight: 2
    range:
      - 63
      - 64
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.3znV7LBRbXYiQuMo'
  - _id: hLu3UNN9kcJulB5M
    flags: {}
    type: text
    text: Excellence in one’s profession or trade
    weight: 2
    range:
      - 65
      - 66
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hLu3UNN9kcJulB5M'
  - _id: MaVAkI9wNP2jmtCT
    flags: {}
    type: text
    text: Loyalty to one’s friends, family, and own
    weight: 2
    range:
      - 67
      - 68
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.MaVAkI9wNP2jmtCT'
  - _id: GCEvdvdtrHB83X5I
    flags: {}
    type: text
    text: Vengeance and execution of just vendettas
    weight: 2
    range:
      - 69
      - 70
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.GCEvdvdtrHB83X5I'
  - _id: KyQcgE8y1WCR9amN
    flags: {}
    type: text
    text: Restoring some real or imagined glorious past
    weight: 2
    range:
      - 71
      - 72
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.KyQcgE8y1WCR9amN'
  - _id: rQyAzq5j0MSzDzoR
    flags: {}
    type: text
    text: Unity and elimination of group differences
    weight: 2
    range:
      - 73
      - 74
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.rQyAzq5j0MSzDzoR'
  - _id: hsHOM8xTeiJpoSf5
    flags: {}
    type: text
    text: Magical prowess and occult ability
    weight: 2
    range:
      - 75
      - 76
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hsHOM8xTeiJpoSf5'
  - _id: WylvnuYr3nc7MIC8
    flags: {}
    type: text
    text: Sharing wealth and goods with others
    weight: 2
    range:
      - 77
      - 78
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.WylvnuYr3nc7MIC8'
  - _id: W36pC9d6HCp0imPO
    flags: {}
    type: text
    text: Membership in an elite bloodline or caste
    weight: 2
    range:
      - 79
      - 80
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.W36pC9d6HCp0imPO'
  - _id: F6nYpXMI3Mm6Lxe1
    flags: {}
    type: text
    text: Personal indulgence and luxuriant pleasure
    weight: 2
    range:
      - 81
      - 82
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.F6nYpXMI3Mm6Lxe1'
  - _id: UKnCtXBnXMVGetOt
    flags: {}
    type: text
    text: Scheming subtly against enemies or rivals
    weight: 2
    range:
      - 83
      - 84
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.UKnCtXBnXMVGetOt'
  - _id: bdzrF3BR87x4grUU
    flags: {}
    type: text
    text: Remembrance of the past and memorializing history
    weight: 2
    range:
      - 85
      - 86
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.bdzrF3BR87x4grUU'
  - _id: g41LzU573bWTjGV2
    flags: {}
    type: text
    text: Aesthetic beauty in material goods and architecture
    weight: 2
    range:
      - 87
      - 88
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.g41LzU573bWTjGV2'
  - _id: Hm0J1p2ot5Rb9TFW
    flags: {}
    type: text
    text: Zealous guardianship of their own land or holy sites
    weight: 2
    range:
      - 89
      - 90
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.Hm0J1p2ot5Rb9TFW'
  - _id: clZ9po4EYTOKKn88
    flags: {}
    type: text
    text: Humanistic reason and “rational” religion
    weight: 2
    range:
      - 91
      - 92
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.clZ9po4EYTOKKn88'
  - _id: XOfEMWcSX7ZJQ6UL
    flags: {}
    type: text
    text: Industry and the ability to work tirelessly
    weight: 2
    range:
      - 93
      - 94
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.XOfEMWcSX7ZJQ6UL'
  - _id: m03gFj04N6zY1VOh
    flags: {}
    type: text
    text: Leadership and charisma in the group
    weight: 2
    range:
      - 95
      - 96
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.m03gFj04N6zY1VOh'
  - _id: HCLpZXTzQrRcgupc
    flags: {}
    type: text
    text: Pacifism and peaceful resolution of problems
    weight: 2
    range:
      - 97
      - 98
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.HCLpZXTzQrRcgupc'
  - _id: hITuh7WBGygjz7KT
    flags: {}
    type: text
    text: Societal or ethnic superiority over all outsiders
    weight: 2
    range:
      - 99
      - 100
    drawn: false
    img: null
    documentId: null
    _key: '!tables.results!7nxDYi7V2mtlvqmV.hITuh7WBGygjz7KT'
formula: 1d100
replacement: true
displayRoll: true
folder: null
sort: 1000000
flags:
  better-rolltables: {}
ownership:
  default: 0
  mgBwP0sTLP1VFg1m: 3
_stats:
  systemId: wwn
  systemVersion: 1.1.4
  coreVersion: '12.324'
  createdTime: null
  modifiedTime: 1690569840132
  lastModifiedBy: VPYTJCONjTybUwoI
  compendiumSource: null
  duplicateSource: null
_key: '!tables!7nxDYi7V2mtlvqmV'

