_id: h655f580m3jdw3sx
name: Atmospheric configuration
type: shipFitting
img: systems/swnr/assets/icons/game-icons.net/item-icons/power-generator.svg
folder: FSb3IGBn6eTDHX2S
sort: 0
ownership:
  default: 0
  iXDXVi7OlHcRwXw0: 3
flags: {}
_stats:
  compendiumSource: Compendium.swnr.ship-fitting.Item.h655f580m3jdw3sx
  duplicateSource: null
  exportSource: null
  coreVersion: '13.346'
  systemId: swnr
  systemVersion: 2.1.0-beta
  createdTime: 1757286946146
  modifiedTime: 1757286946146
  lastModifiedBy: iXDXVi7OlHcRwXw0
system:
  broken: false
  cost: 5000
  costMultiplier: true
  description: >-
    This fitting must be put in place when the ship is built, and cannot be
    installed on cruiser-class or larger ships. A ship designed for atmospheric
    flight can land on most solid or aqueous surfaces.
  destroyed: false
  effect: 'Can land: frigates and fighters only.'
  favorite: false
  juryRigged: false
  mass: 1
  massMultiplier: true
  minClass: fighter
  power: 0
  powerMultiplier: false
  tl: 4
  type: ship
effects: []
_key: '!items!h655f580m3jdw3sx'

