type: Item
folder: kwpVu6q9SLVqat1K
name: Trained List
color: null
sorting: a
_id: XaiAMiW4FIajEZMb
description: ''
sort: 200000
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  exportSource: null
  coreVersion: '13.350'
  systemId: swnr
  systemVersion: 2.2.0
  createdTime: 1761533229270
  modifiedTime: 1761533229270
  lastModifiedBy: iXDXVi7OlHcRwXw0
_key: '!folders!XaiAMiW4FIajEZMb'

