name: Prodigy
type: feature
img: systems/swnr/assets/icons/game-icons.net/item-icons/edge.svg
folder: bmlxot0Gn0smSX1W
flags: {}
_stats:
  compendiumSource: Compendium.swnr.cwn-edges.Item.3vkunhznrha449o0
  duplicateSource: null
  exportSource: null
  coreVersion: '13.346'
  systemId: swnr
  systemVersion: 2.1.0
  createdTime: 1754266777803
  modifiedTime: 1754266777803
  lastModifiedBy: lKC5x4Yf023Bizof
system:
  description: >-
    Pick an attribute other than Constitution; its score becomes 18 and it
    grants a +3 modifier instead of +2. Characters benefiting from the Underdog
    Rule can't take this Edge.
  favorite: false
  level: 0
  type: edge
  poolsGranted: []
effects: []
ownership:
  default: 0
  lKC5x4Yf023Bizof: 3
_id: 8kXOkFRT2fVLDcqF
sort: 0
_key: '!items!8kXOkFRT2fVLDcqF'

