name: Atmospheric configuration
type: shipFitting
img: systems/swnr/assets/icons/game-icons.net/item-icons/power-generator.svg
folder: null
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  coreVersion: '12.331'
  systemId: swnr
  systemVersion: 2.0.0
  createdTime: 1739238988985
  modifiedTime: 1739238988985
sort: 0
_id: fnyermghz9nd6vpa
system: {}
effects: []
_key: '!items!fnyermghz9nd6vpa'
